import GlobalLayout from "@/app/layouts/global";

import type { ReactNode } from "react";
import type { Metadata } from "next";

import "./globals.css";

interface Props {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Props>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <GlobalLayout>
                    {children}
                </GlobalLayout>
            </body>
        </html>
    );
}
