import LeftToolBarPage from "@/app/components/letf-tool-bar/page";

import "./globals.css";
import "./layout.css";

import type { ReactNode } from "react";
import type { Metadata } from "next";

interface Props {
    children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main>
            <LeftToolBarPage />
            <div className="content">
                {children}
            </div>
        </main>
      </body>
    </html>
  );
}
